name: Build-Inputer

on:
  push:
    paths:
    - '**.py'
    - '**.yml'
  pull_request:
    paths:
    - '**.py'
    - '**.yml'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]

    steps:
    - name: Set Up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

    - name: Build For Windows/Mac/Linux
      run: |
        pyinstaller -F 'Gfriends Inputer.py' --collect-all grapheme

      - name: Copy config.ini
        run: |
          cp ./Lib/opencv_face_detector_uint8.pb ./dist/Lib/opencv_face_detector_uint8.pb
          cp ./Lib/opencv_face_detector.pbtxt ./dist/Lib/opencv_face_detector.pbtxt

    - name: Upload Build Artifact
      uses: actions/upload-artifact@v1
      with:
        name: Gfriends-Inputer-${{ runner.os }}
        path: dist
